// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBk_-R7ck6nz77ke45PfFE14zqQfODJ3Q',
    appId: '1:877866277570:web:6c4a5ac634a6c24b91795b',
    messagingSenderId: '877866277570',
    projectId: 'sirmo-736ef',
    authDomain: 'sirmo-736ef.firebaseapp.com',
    databaseURL: 'https://sirmo-736ef-default-rtdb.firebaseio.com',
    storageBucket: 'sirmo-736ef.appspot.com',
    measurementId: 'G-GLGEX7WCY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwFroAbktFHgJczR6oCsDdLsrmAX7RqA',
    appId: '1:877866277570:android:e5fe8339eda4487791795b',
    messagingSenderId: '877866277570',
    projectId: 'sirmo-736ef',
    databaseURL: 'https://sirmo-736ef-default-rtdb.firebaseio.com',
    storageBucket: 'sirmo-736ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyVXbCvQPcLysbWrIaS1hUkD9EoODS3Qg',
    appId: '1:877866277570:ios:024fa213ead27be391795b',
    messagingSenderId: '877866277570',
    projectId: 'sirmo-736ef',
    databaseURL: 'https://sirmo-736ef-default-rtdb.firebaseio.com',
    storageBucket: 'sirmo-736ef.appspot.com',
    iosClientId: '877866277570-b2qbevsjo0dlrbl6uogstmj4d5kncft5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sirmo',
  );
}
