export enum ConstanteVisibility{
    PUBLIC="PUBLIC",
    PRIVEE="PRIVEE",
    INFORMATICIEN = 'INFORMATICIEN',
    ADMIN = 'ADMIN',
    MANAGER = 'MANAGER',
    MAIRIE = 'MAIRIE',
    POLICE = 'POLICE',
    ZEM = 'ZEM',
    PROPRIETAIRE = 'PROPRIETAIRE',
    USER = 'USER',
    ECOBANCK = 'ECOBANCK'
}