/* eslint-disable prettier/prettier */
export enum TypeOperation {
    RECHARGEMENT_PAR_ECOBANK = 'RECHARGEMENT PAR ECOBANK',
    RECHARGEMENT_PAR_FEDAPAY = 'RECHARGEMENT PAR FEDAPAY',
    PAYEMENT_AMANDE = "PAYEMENT D'AMANDE",
    PAYEMENT_LICENCE = 'PAYEMENT DE LICENCE',
    PAYEMENT_LICENCE_BY_ADMIN = "PAYEMENT DE LICENCE A L'AGENCE",
    PAYEMENT_LICENCE_VEHICULE = "PAYEMENT DE LA LICENCE DU VEHICULE ",
    PAYEMENT_LICENCE_VEHICULE_BY_ADMIN  = "PAYEMENT DE LA LICENCE DU VEHICULE A L'AGENCE",
    RETRAIT = 'RETRAIT',
    PAYEMENT_CONDUCTEUR = "PAYER CONDUCTEUR",
  }
  