/* eslint-disable prettier/prettier */
export enum TypeOperation {
    RECHARGEMENT_PAR_ECOBANK = 'RECHARGEMENT PAR ECOBANK',
    RECHARGEMENT_PAR_FEDAPAY = 'RECHARGEMENT PAR FEDAPAY',
    PAYEMENT_AMANDE = "PAYEMENT D'AMANDE",
    PAYEMENT_LICENCE = 'PAYEMENT DE LICENCE',
    RETRAIT = 'RETRAIT',
    
  }
  