import {MigrationInterface, QueryRunner} from "typeorm";

export class all1651659914223 implements MigrationInterface {
    name = 'all1651659914223'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "departement" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, CONSTRAINT "PK_f32f7be16ef46566fececc35a34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commune" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "departement_id" integer NOT NULL, CONSTRAINT "PK_bc512eb8412b43c9dc6e2c9e683" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "arrondissement" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "commune_id" integer NOT NULL, CONSTRAINT "PK_ab364ef43abdb59b581b94f358e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "localisations" ("id" SERIAL NOT NULL, "longitude" integer NOT NULL, "latitude" integer NOT NULL, "altitude" integer NOT NULL, "speed" integer NOT NULL, "accuracy" integer NOT NULL, "entity" character varying NOT NULL, "entityId" integer NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cecebf81ea14cb74369a811961d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fichier" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "path" character varying NOT NULL, "mimetype" character varying NOT NULL, "size" character varying NOT NULL, "entity" character varying NOT NULL, "entityId" integer NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c2db0417e096e1fde1a13cc378c" UNIQUE ("path"), CONSTRAINT "PK_35788b04279085d084bae7bfe52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mairies" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "adresse" character varying NOT NULL, "couleur" character varying NOT NULL DEFAULT '#00561b', "solde" integer NOT NULL DEFAULT '0', "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "arrondissement_id" integer, "localisation_id" integer, "commune_id" integer NOT NULL, "fichier_id" integer, CONSTRAINT "UQ_5eb4b53596c495fbe8868538c7d" UNIQUE ("nom"), CONSTRAINT "REL_4ea43fd063892b8a2a21ce66cd" UNIQUE ("commune_id"), CONSTRAINT "PK_a4e62e56e8d68ad97d98536f5f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "compte" ("id" integer NOT NULL, "montant" integer NOT NULL, "cip" character varying NOT NULL, CONSTRAINT "UQ_dcde39cd2ac67a84ad411ec6e1b" UNIQUE ("cip"), CONSTRAINT "REL_fe8b9e894bf80fbe677b14f9f8" UNIQUE ("id"), CONSTRAINT "PK_fe8b9e894bf80fbe677b14f9f8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payement" ("id" SERIAL NOT NULL, "montant" integer NOT NULL, "solde" integer NOT NULL, "type" character varying NOT NULL, "operation" character varying NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "compte_id" integer, CONSTRAINT "PK_de97e258d2497a6293e7d92b9b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "licence" ("id" SERIAL NOT NULL, "montant" integer NOT NULL, "date_debut" TIMESTAMP NOT NULL DEFAULT NOW(), "date_fin" TIMESTAMP NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "zem_id" integer, "marie" integer NOT NULL, "payement" integer, CONSTRAINT "PK_3b4f2cda4a38b8026e4c700844c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bf38105dbf51728ebae7ed542a4" UNIQUE ("nom"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "prenom" character varying NOT NULL, "genre" boolean NOT NULL, "password" character varying NOT NULL, "email" character varying NOT NULL, "date_naiss" TIMESTAMP NOT NULL, "tel" character varying NOT NULL, "code" character varying NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "arrondissement_id" integer NOT NULL, "fichier_id" integer, CONSTRAINT "UQ_ff716f76b4bf8176aa40d0c87ce" UNIQUE ("tel"), CONSTRAINT "UQ_c5f78ad8f82e492c25d07f047a5" UNIQUE ("code"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proprietaire_moto" ("id" SERIAL NOT NULL, "date_debut" TIMESTAMP NOT NULL DEFAULT NOW(), "date_fin" TIMESTAMP NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "proprietaire_id" integer NOT NULL, "moto_id" integer NOT NULL, CONSTRAINT "PK_3a133b29ea68e55bbf504550626" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "moto" ("id" SERIAL NOT NULL, "matricule" character varying NOT NULL, "carteGrise" character varying NOT NULL, "chassis" character varying NOT NULL, "serie" character varying NOT NULL, "etat" character varying NOT NULL DEFAULT 'OCASION', "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "proprietaire_id" integer, "zem_id" integer, "fichier_id" integer, CONSTRAINT "UQ_fbe54b5e97b12bb2b6409ca5771" UNIQUE ("matricule"), CONSTRAINT "UQ_74ffbc8efc66eaf4f9f291454aa" UNIQUE ("carteGrise"), CONSTRAINT "UQ_ecdcf53c5ece0c6215a64c3ec6d" UNIQUE ("chassis"), CONSTRAINT "UQ_9bbf092b6819723dc560e127a15" UNIQUE ("serie"), CONSTRAINT "PK_baf054ef185a2926f3585b462ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "appreciation" ("id" SERIAL NOT NULL, "typeAppreciation" character varying NOT NULL, "message" character varying NOT NULL, "tel" character varying NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "zem_id" integer NOT NULL, "fichier_id" integer, CONSTRAINT "PK_d9824c8e198e82f7394c805eddf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "zem_moto" ("id" SERIAL NOT NULL, "date_debut" TIMESTAMP NOT NULL DEFAULT NOW(), "date_fin" TIMESTAMP NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "zem_id" integer NOT NULL, "moto_id" integer NOT NULL, CONSTRAINT "PK_444681cf3aff801bcc8314d0448" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "zem" ("id" integer NOT NULL, "ifu" character varying NOT NULL, "cip" character varying NOT NULL, "nip" character varying NOT NULL, "niz" character varying NOT NULL, "compteEcobank" character varying NOT NULL, "compteFedapay" character varying NOT NULL, "certificatRoute" character varying NOT NULL, "statut" character varying NOT NULL, "ancienIdentifiant" character varying NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "licence_id" integer, "moto_id" integer, CONSTRAINT "UQ_82bb5f9a6d551375ff5f54add07" UNIQUE ("ifu"), CONSTRAINT "UQ_bc4d4148f9ae83447b8342da6b6" UNIQUE ("cip"), CONSTRAINT "UQ_6588aeee414ff0158a4c889f5ac" UNIQUE ("nip"), CONSTRAINT "UQ_bb18427c5b7a89b1fcbe40ac10b" UNIQUE ("niz"), CONSTRAINT "UQ_17f5f57956378db352ca17f14c4" UNIQUE ("compteEcobank"), CONSTRAINT "UQ_0d9d1ef9388c3ca4e72aa3928c3" UNIQUE ("compteFedapay"), CONSTRAINT "UQ_397d74f998106a24ece032aca22" UNIQUE ("certificatRoute"), CONSTRAINT "REL_309eaf8e98ac9bfbca4b7ee2ea" UNIQUE ("id"), CONSTRAINT "PK_309eaf8e98ac9bfbca4b7ee2ea8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "type_amande" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "montant" integer NOT NULL, "description" character varying NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "fichier_id" integer, CONSTRAINT "PK_acc7c9720d5753f6434308bae2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "police" ("id" integer NOT NULL, "ifu" character varying NOT NULL, "identifiant" character varying NOT NULL, "createur_id" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_de957f5b376a96e068741b3f696" UNIQUE ("ifu"), CONSTRAINT "UQ_55bf7cc55f04fd2d2c7023446b0" UNIQUE ("identifiant"), CONSTRAINT "REL_c8a3a10755aaad235fd9fbee69" UNIQUE ("id"), CONSTRAINT "PK_c8a3a10755aaad235fd9fbee699" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "amande" ("id" SERIAL NOT NULL, "message" character varying NOT NULL, "montant" integer NOT NULL, "date_limite" TIMESTAMP NOT NULL, "restant" integer NOT NULL, "editeur_id" integer NOT NULL, "create_at" TIMESTAMP NOT NULL DEFAULT now(), "update_at" TIMESTAMP NOT NULL DEFAULT now(), "police_id" integer, "zem_id" integer NOT NULL, CONSTRAINT "PK_ed9abcd56592a7dd2b8a70250a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mairie_images" ("mairie_id" integer NOT NULL, "fichier_id" integer NOT NULL, CONSTRAINT "PK_0552dfb5c95fe2daa6f86d3dd28" PRIMARY KEY ("mairie_id", "fichier_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac71c8a595bcd8a8c89d3b9b77" ON "mairie_images" ("mairie_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_29b641055afe00e7053af5b6f3" ON "mairie_images" ("fichier_id") `);
        await queryRunner.query(`CREATE TABLE "users_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_c525e9373d63035b9919e578a9c" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e4435209df12bc1f001e536017" ON "users_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1cf664021f00b9cc1ff95e17de" ON "users_roles" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "users_profiles" ("user_id" integer NOT NULL, "fichier_id" integer NOT NULL, CONSTRAINT "PK_65d0e006b1d4d2d176e8a5a8785" PRIMARY KEY ("user_id", "fichier_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_181a055631e557898c3eea0f37" ON "users_profiles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7a5b3c88243b792de167a6613" ON "users_profiles" ("fichier_id") `);
        await queryRunner.query(`CREATE TABLE "motos_images" ("moto_id" integer NOT NULL, "fichier_id" integer NOT NULL, CONSTRAINT "PK_df0e08bfb6ec898fa87476614c6" PRIMARY KEY ("moto_id", "fichier_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a8759c626990209d4f7d4b515a" ON "motos_images" ("moto_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_792a4c0a7d6ee7e6d361663152" ON "motos_images" ("fichier_id") `);
        await queryRunner.query(`CREATE TABLE "amande_types" ("amande_id" integer NOT NULL, "type_amande_id" integer NOT NULL, CONSTRAINT "PK_f6ec2be58f8a32a451552418a1e" PRIMARY KEY ("amande_id", "type_amande_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ddccb203df29a7f8dafa9694a" ON "amande_types" ("amande_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd9ddc927cf2cc5686ca60e69e" ON "amande_types" ("type_amande_id") `);
        await queryRunner.query(`CREATE TABLE "amandes_payements" ("amande_id" integer NOT NULL, "payement_id" integer NOT NULL, CONSTRAINT "PK_7753a59f0dd1e727a2645a9763b" PRIMARY KEY ("amande_id", "payement_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db10737d2118e3aa77d972b274" ON "amandes_payements" ("amande_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_214278edf9176cb8988eb38931" ON "amandes_payements" ("payement_id") `);
        await queryRunner.query(`ALTER TABLE "commune" ADD CONSTRAINT "FK_d3feff61d835fc49adbf6b4a1e3" FOREIGN KEY ("departement_id") REFERENCES "departement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arrondissement" ADD CONSTRAINT "FK_fb7b62af81264399757211dbd00" FOREIGN KEY ("commune_id") REFERENCES "commune"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairies" ADD CONSTRAINT "FK_564e0bf23e1e1be80b8a0489568" FOREIGN KEY ("arrondissement_id") REFERENCES "arrondissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairies" ADD CONSTRAINT "FK_c4a3066ced3ef3846ee57d5165e" FOREIGN KEY ("localisation_id") REFERENCES "localisations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairies" ADD CONSTRAINT "FK_4ea43fd063892b8a2a21ce66cd0" FOREIGN KEY ("commune_id") REFERENCES "commune"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairies" ADD CONSTRAINT "FK_8f6114a983a41e56fa95451ae63" FOREIGN KEY ("fichier_id") REFERENCES "fichier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "compte" ADD CONSTRAINT "FK_fe8b9e894bf80fbe677b14f9f8c" FOREIGN KEY ("id") REFERENCES "zem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payement" ADD CONSTRAINT "FK_77f9e3ac513490b55c462ef4bcb" FOREIGN KEY ("compte_id") REFERENCES "compte"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licence" ADD CONSTRAINT "FK_3e58fa1214dda608751cb339f4a" FOREIGN KEY ("zem_id") REFERENCES "zem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licence" ADD CONSTRAINT "FK_b35e72843c0a6fee181fd9c9440" FOREIGN KEY ("marie") REFERENCES "mairies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licence" ADD CONSTRAINT "FK_db77ad2d5bf8eae1083871b03f8" FOREIGN KEY ("payement") REFERENCES "payement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_ec2f4df8acad5d6754df36ba09c" FOREIGN KEY ("arrondissement_id") REFERENCES "arrondissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_9f60fe0865222ac74a9e8840ae1" FOREIGN KEY ("fichier_id") REFERENCES "fichier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proprietaire_moto" ADD CONSTRAINT "FK_6440bbadf625a4895db8223a74f" FOREIGN KEY ("proprietaire_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proprietaire_moto" ADD CONSTRAINT "FK_c5e80a8fecabf2ef6c5b1639fbf" FOREIGN KEY ("moto_id") REFERENCES "moto"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moto" ADD CONSTRAINT "FK_91a9cc07f6c9568c324389ca6a0" FOREIGN KEY ("proprietaire_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moto" ADD CONSTRAINT "FK_3b4b027222c3c8e455c25a547c6" FOREIGN KEY ("zem_id") REFERENCES "zem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moto" ADD CONSTRAINT "FK_235399dfd7ec9b39fb3819019a2" FOREIGN KEY ("fichier_id") REFERENCES "fichier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appreciation" ADD CONSTRAINT "FK_84112a071644374aa4ef5ae1058" FOREIGN KEY ("zem_id") REFERENCES "zem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appreciation" ADD CONSTRAINT "FK_954761cacf5a5335b74a67e34a0" FOREIGN KEY ("fichier_id") REFERENCES "fichier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zem_moto" ADD CONSTRAINT "FK_ae11515b2c670c2f28dc6ea1fef" FOREIGN KEY ("zem_id") REFERENCES "zem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zem_moto" ADD CONSTRAINT "FK_424224cd534895498a16e93e3bf" FOREIGN KEY ("moto_id") REFERENCES "moto"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zem" ADD CONSTRAINT "FK_309eaf8e98ac9bfbca4b7ee2ea8" FOREIGN KEY ("id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zem" ADD CONSTRAINT "FK_465fae2a410cf6418984dab7d76" FOREIGN KEY ("licence_id") REFERENCES "licence"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zem" ADD CONSTRAINT "FK_444681cf3aff801bcc8314d0448" FOREIGN KEY ("moto_id") REFERENCES "moto"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "type_amande" ADD CONSTRAINT "FK_d5c3e0a82657e74ab3ad0362e12" FOREIGN KEY ("fichier_id") REFERENCES "fichier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "police" ADD CONSTRAINT "FK_c8a3a10755aaad235fd9fbee699" FOREIGN KEY ("id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amande" ADD CONSTRAINT "FK_a9405e30e98c65fafec669c7893" FOREIGN KEY ("police_id") REFERENCES "police"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amande" ADD CONSTRAINT "FK_73393aa0ce2d39f2d71a043e8bc" FOREIGN KEY ("zem_id") REFERENCES "zem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairie_images" ADD CONSTRAINT "FK_ac71c8a595bcd8a8c89d3b9b779" FOREIGN KEY ("mairie_id") REFERENCES "mairies"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mairie_images" ADD CONSTRAINT "FK_29b641055afe00e7053af5b6f32" FOREIGN KEY ("fichier_id") REFERENCES "fichier"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_roles" ADD CONSTRAINT "FK_e4435209df12bc1f001e5360174" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_roles" ADD CONSTRAINT "FK_1cf664021f00b9cc1ff95e17de4" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_profiles" ADD CONSTRAINT "FK_181a055631e557898c3eea0f37e" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_profiles" ADD CONSTRAINT "FK_a7a5b3c88243b792de167a66135" FOREIGN KEY ("fichier_id") REFERENCES "fichier"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "motos_images" ADD CONSTRAINT "FK_a8759c626990209d4f7d4b515a5" FOREIGN KEY ("moto_id") REFERENCES "moto"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "motos_images" ADD CONSTRAINT "FK_792a4c0a7d6ee7e6d3616631521" FOREIGN KEY ("fichier_id") REFERENCES "fichier"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "amande_types" ADD CONSTRAINT "FK_3ddccb203df29a7f8dafa9694a3" FOREIGN KEY ("amande_id") REFERENCES "amande"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "amande_types" ADD CONSTRAINT "FK_cd9ddc927cf2cc5686ca60e69ec" FOREIGN KEY ("type_amande_id") REFERENCES "type_amande"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "amandes_payements" ADD CONSTRAINT "FK_db10737d2118e3aa77d972b274e" FOREIGN KEY ("amande_id") REFERENCES "amande"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "amandes_payements" ADD CONSTRAINT "FK_214278edf9176cb8988eb38931a" FOREIGN KEY ("payement_id") REFERENCES "payement"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "amandes_payements" DROP CONSTRAINT "FK_214278edf9176cb8988eb38931a"`);
        await queryRunner.query(`ALTER TABLE "amandes_payements" DROP CONSTRAINT "FK_db10737d2118e3aa77d972b274e"`);
        await queryRunner.query(`ALTER TABLE "amande_types" DROP CONSTRAINT "FK_cd9ddc927cf2cc5686ca60e69ec"`);
        await queryRunner.query(`ALTER TABLE "amande_types" DROP CONSTRAINT "FK_3ddccb203df29a7f8dafa9694a3"`);
        await queryRunner.query(`ALTER TABLE "motos_images" DROP CONSTRAINT "FK_792a4c0a7d6ee7e6d3616631521"`);
        await queryRunner.query(`ALTER TABLE "motos_images" DROP CONSTRAINT "FK_a8759c626990209d4f7d4b515a5"`);
        await queryRunner.query(`ALTER TABLE "users_profiles" DROP CONSTRAINT "FK_a7a5b3c88243b792de167a66135"`);
        await queryRunner.query(`ALTER TABLE "users_profiles" DROP CONSTRAINT "FK_181a055631e557898c3eea0f37e"`);
        await queryRunner.query(`ALTER TABLE "users_roles" DROP CONSTRAINT "FK_1cf664021f00b9cc1ff95e17de4"`);
        await queryRunner.query(`ALTER TABLE "users_roles" DROP CONSTRAINT "FK_e4435209df12bc1f001e5360174"`);
        await queryRunner.query(`ALTER TABLE "mairie_images" DROP CONSTRAINT "FK_29b641055afe00e7053af5b6f32"`);
        await queryRunner.query(`ALTER TABLE "mairie_images" DROP CONSTRAINT "FK_ac71c8a595bcd8a8c89d3b9b779"`);
        await queryRunner.query(`ALTER TABLE "amande" DROP CONSTRAINT "FK_73393aa0ce2d39f2d71a043e8bc"`);
        await queryRunner.query(`ALTER TABLE "amande" DROP CONSTRAINT "FK_a9405e30e98c65fafec669c7893"`);
        await queryRunner.query(`ALTER TABLE "police" DROP CONSTRAINT "FK_c8a3a10755aaad235fd9fbee699"`);
        await queryRunner.query(`ALTER TABLE "type_amande" DROP CONSTRAINT "FK_d5c3e0a82657e74ab3ad0362e12"`);
        await queryRunner.query(`ALTER TABLE "zem" DROP CONSTRAINT "FK_444681cf3aff801bcc8314d0448"`);
        await queryRunner.query(`ALTER TABLE "zem" DROP CONSTRAINT "FK_465fae2a410cf6418984dab7d76"`);
        await queryRunner.query(`ALTER TABLE "zem" DROP CONSTRAINT "FK_309eaf8e98ac9bfbca4b7ee2ea8"`);
        await queryRunner.query(`ALTER TABLE "zem_moto" DROP CONSTRAINT "FK_424224cd534895498a16e93e3bf"`);
        await queryRunner.query(`ALTER TABLE "zem_moto" DROP CONSTRAINT "FK_ae11515b2c670c2f28dc6ea1fef"`);
        await queryRunner.query(`ALTER TABLE "appreciation" DROP CONSTRAINT "FK_954761cacf5a5335b74a67e34a0"`);
        await queryRunner.query(`ALTER TABLE "appreciation" DROP CONSTRAINT "FK_84112a071644374aa4ef5ae1058"`);
        await queryRunner.query(`ALTER TABLE "moto" DROP CONSTRAINT "FK_235399dfd7ec9b39fb3819019a2"`);
        await queryRunner.query(`ALTER TABLE "moto" DROP CONSTRAINT "FK_3b4b027222c3c8e455c25a547c6"`);
        await queryRunner.query(`ALTER TABLE "moto" DROP CONSTRAINT "FK_91a9cc07f6c9568c324389ca6a0"`);
        await queryRunner.query(`ALTER TABLE "proprietaire_moto" DROP CONSTRAINT "FK_c5e80a8fecabf2ef6c5b1639fbf"`);
        await queryRunner.query(`ALTER TABLE "proprietaire_moto" DROP CONSTRAINT "FK_6440bbadf625a4895db8223a74f"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_9f60fe0865222ac74a9e8840ae1"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_ec2f4df8acad5d6754df36ba09c"`);
        await queryRunner.query(`ALTER TABLE "licence" DROP CONSTRAINT "FK_db77ad2d5bf8eae1083871b03f8"`);
        await queryRunner.query(`ALTER TABLE "licence" DROP CONSTRAINT "FK_b35e72843c0a6fee181fd9c9440"`);
        await queryRunner.query(`ALTER TABLE "licence" DROP CONSTRAINT "FK_3e58fa1214dda608751cb339f4a"`);
        await queryRunner.query(`ALTER TABLE "payement" DROP CONSTRAINT "FK_77f9e3ac513490b55c462ef4bcb"`);
        await queryRunner.query(`ALTER TABLE "compte" DROP CONSTRAINT "FK_fe8b9e894bf80fbe677b14f9f8c"`);
        await queryRunner.query(`ALTER TABLE "mairies" DROP CONSTRAINT "FK_8f6114a983a41e56fa95451ae63"`);
        await queryRunner.query(`ALTER TABLE "mairies" DROP CONSTRAINT "FK_4ea43fd063892b8a2a21ce66cd0"`);
        await queryRunner.query(`ALTER TABLE "mairies" DROP CONSTRAINT "FK_c4a3066ced3ef3846ee57d5165e"`);
        await queryRunner.query(`ALTER TABLE "mairies" DROP CONSTRAINT "FK_564e0bf23e1e1be80b8a0489568"`);
        await queryRunner.query(`ALTER TABLE "arrondissement" DROP CONSTRAINT "FK_fb7b62af81264399757211dbd00"`);
        await queryRunner.query(`ALTER TABLE "commune" DROP CONSTRAINT "FK_d3feff61d835fc49adbf6b4a1e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_214278edf9176cb8988eb38931"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db10737d2118e3aa77d972b274"`);
        await queryRunner.query(`DROP TABLE "amandes_payements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd9ddc927cf2cc5686ca60e69e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddccb203df29a7f8dafa9694a"`);
        await queryRunner.query(`DROP TABLE "amande_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_792a4c0a7d6ee7e6d361663152"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8759c626990209d4f7d4b515a"`);
        await queryRunner.query(`DROP TABLE "motos_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7a5b3c88243b792de167a6613"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_181a055631e557898c3eea0f37"`);
        await queryRunner.query(`DROP TABLE "users_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cf664021f00b9cc1ff95e17de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4435209df12bc1f001e536017"`);
        await queryRunner.query(`DROP TABLE "users_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29b641055afe00e7053af5b6f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac71c8a595bcd8a8c89d3b9b77"`);
        await queryRunner.query(`DROP TABLE "mairie_images"`);
        await queryRunner.query(`DROP TABLE "amande"`);
        await queryRunner.query(`DROP TABLE "police"`);
        await queryRunner.query(`DROP TABLE "type_amande"`);
        await queryRunner.query(`DROP TABLE "zem"`);
        await queryRunner.query(`DROP TABLE "zem_moto"`);
        await queryRunner.query(`DROP TABLE "appreciation"`);
        await queryRunner.query(`DROP TABLE "moto"`);
        await queryRunner.query(`DROP TABLE "proprietaire_moto"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "licence"`);
        await queryRunner.query(`DROP TABLE "payement"`);
        await queryRunner.query(`DROP TABLE "compte"`);
        await queryRunner.query(`DROP TABLE "mairies"`);
        await queryRunner.query(`DROP TABLE "fichier"`);
        await queryRunner.query(`DROP TABLE "localisations"`);
        await queryRunner.query(`DROP TABLE "arrondissement"`);
        await queryRunner.query(`DROP TABLE "commune"`);
        await queryRunner.query(`DROP TABLE "departement"`);
    }

}
