import {MigrationInterface, QueryRunner} from "typeorm";

export class zemPlus1657723252615 implements MigrationInterface {
    name = 'zemPlus1657723252615'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "departements" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, CONSTRAINT "PK_2c4850823d8f6ec267b042368da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "communes" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "departement_id" integer NOT NULL, CONSTRAINT "PK_53a9285bb669dd2298c4de525bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "arrondissements" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "commune_id" integer NOT NULL, CONSTRAINT "PK_e063443c54ae627495ab180c24d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "localisations" ("id" SERIAL NOT NULL, "longitude" integer NOT NULL, "latitude" integer NOT NULL, "altitude" integer NOT NULL, "place_id" character varying NOT NULL, "entity" character varying NOT NULL, "entityId" integer NOT NULL, CONSTRAINT "PK_cecebf81ea14cb74369a811961d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fichiers" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "nom" character varying, "path" character varying NOT NULL, "mimetype" character varying, "size" character varying, "entity" character varying, "entityId" integer, CONSTRAINT "UQ_50bae38579eacbd9d68347d6c55" UNIQUE ("path"), CONSTRAINT "PK_bca2fb50f754cc037cdf251ca9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mairies" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "nom" character varying NOT NULL, "adresse" character varying NOT NULL, "couleur" character varying NOT NULL DEFAULT '#00561b', "solde" integer NOT NULL DEFAULT '0', "accumulation" integer NOT NULL DEFAULT '0', "arrondissement_id" integer, "localisation_id" integer, "commune_id" integer NOT NULL, "fichier_id" integer, CONSTRAINT "UQ_5eb4b53596c495fbe8868538c7d" UNIQUE ("nom"), CONSTRAINT "REL_4ea43fd063892b8a2a21ce66cd" UNIQUE ("commune_id"), CONSTRAINT "PK_a4e62e56e8d68ad97d98536f5f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "nom" character varying NOT NULL, "prenom" character varying NOT NULL, "genre" character varying NOT NULL, "password" character varying NOT NULL, "email" character varying, "date_naiss" TIMESTAMP, "phone" character varying NOT NULL, "code" character varying NOT NULL, "roles" text NOT NULL DEFAULT '["USER"]', "arrondissement_id" integer NOT NULL, "fichier_id" integer, CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "UQ_1f7a2b11e29b1422a2622beab36" UNIQUE ("code"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_65cbf5fcb331619593ee334c7c" ON "users" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "comptes" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" integer NOT NULL, "montant" integer NOT NULL, "total_in" integer NOT NULL DEFAULT '0', CONSTRAINT "REL_f1e9bf900b9220f91b487aeeef" UNIQUE ("id"), CONSTRAINT "PK_f1e9bf900b9220f91b487aeeefd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payements" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "montant" integer NOT NULL, "solde" integer NOT NULL, "type" character varying NOT NULL, "info" character varying NOT NULL, "operation" character varying NOT NULL, "entity_name" character varying, "entity_id" integer, "compte_id" integer, CONSTRAINT "PK_0988a6cffb711c3c8b9e1090060" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "licences" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "montant" integer NOT NULL, "date_debut" TIMESTAMP NOT NULL DEFAULT NOW(), "date_fin" TIMESTAMP NOT NULL, "conducteur_id" integer, "marie" integer NOT NULL, "payement" integer, CONSTRAINT "PK_78f76903a7e2d2b2ac378fca8d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proprietaires_vehicules" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "date_debut" TIMESTAMP NOT NULL DEFAULT NOW(), "date_fin" TIMESTAMP, "proprietaire_id" integer NOT NULL, "vehicule_id" integer NOT NULL, CONSTRAINT "PK_ddece2415efb9da8abd3150fcf3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conducteurs_vehicules" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "date_debut" TIMESTAMP NOT NULL DEFAULT NOW(), "date_fin" TIMESTAMP, "conducteur_id" integer NOT NULL, "vehicule_id" integer NOT NULL, CONSTRAINT "PK_44b7009b3311f620cd9bf47d3bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "licence_vehicule" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "montant" integer NOT NULL, "solde_mairie" integer, "type_payement" character varying, "transaction_id" character varying, "transaction_info" character varying, "date_debut" TIMESTAMP NOT NULL DEFAULT NOW(), "date_fin" TIMESTAMP NOT NULL, "conducteur_id" integer, "vehicule_id" integer, "marie" integer NOT NULL, CONSTRAINT "PK_3fe7b4e9a9d007ce85ebc09f6ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fa4408a1adedcf78424fab08ed" ON "licence_vehicule" ("transaction_id") WHERE transaction_id IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "vehicules" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "immatriculation" character varying NOT NULL, "niv" character varying, "ci_er" character varying, "pays_immatriculation" character varying, "numero_carte_grise" character varying, "numero_chassis" character varying, "numero_serie_moteur" character varying, "provenance" character varying, "puissance" character varying, "puissance_fiscale" character varying, "carosserie" character varying, "categorie" character varying, "energie" character varying, "annee_mise_circulation" TIMESTAMP NOT NULL, "derniere_revision" TIMESTAMP, "etat" character varying NOT NULL DEFAULT 'OCASION', "marque" character varying, "modele" character varying, "type" character varying, "place_assise" integer NOT NULL DEFAULT '1', "couleur" character varying, "ptac" character varying, "pv" character varying, "cv" character varying, "proprietaire_id" integer, "conducteur_id" integer, "licence_vehicule_id" integer, "fichier_id" integer, CONSTRAINT "PK_ba3a47ea8be2150ea0533653b26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1636cc885be3bcd2cf631f5aff" ON "vehicules" ("niv") WHERE niv IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_922bb175132122adc2c82c631b" ON "vehicules" ("ci_er") WHERE niv IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "appreciations" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "typeAppreciation" character varying NOT NULL, "message" character varying, "phone" character varying NOT NULL, "conducteur_id" integer NOT NULL, "fichier_id" integer, CONSTRAINT "PK_5429de85adc9ee184e1b041e0dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conducteurs" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "ifu" character varying NOT NULL, "date_delivrance_ifu" TIMESTAMP, "cip" character varying NOT NULL, "nip" character varying NOT NULL, "nic" character varying, "idCarde" character varying, "permis" character varying NOT NULL, "date_optention_permis" TIMESTAMP, "statut" character varying NOT NULL DEFAULT 'ACTIF', "ancienIdentifiant" character varying NOT NULL, "profile_image" character varying, "idCarde_image" character varying, "conducteur_id" integer NOT NULL, "licence_id" integer, "mairie_id" integer NOT NULL, "vehicule_id" integer, CONSTRAINT "UQ_0e0f2bac76892438cfaef497ff0" UNIQUE ("permis"), CONSTRAINT "REL_eab56262c5281778a6b22b2ea7" UNIQUE ("conducteur_id"), CONSTRAINT "PK_dd2fb3535bba3387b0a0dabdea5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3dcf8f0efa05bea701379e30ba" ON "conducteurs" ("nic") WHERE nic IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "types_amandes" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "nom" character varying NOT NULL, "montant" integer NOT NULL, "description" character varying NOT NULL, "fichier_id" integer, CONSTRAINT "PK_e439aaddb61198225939d20a36b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "polices" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" integer NOT NULL, "ifu" character varying NOT NULL, "identifiant" character varying NOT NULL, CONSTRAINT "UQ_93e84ac5e05ebda3157cacaa567" UNIQUE ("ifu"), CONSTRAINT "UQ_08d93a26b4426b6bb9267283427" UNIQUE ("identifiant"), CONSTRAINT "REL_c13da5ea9563bc3a99ebf32190" UNIQUE ("id"), CONSTRAINT "PK_c13da5ea9563bc3a99ebf321906" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "amandes" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "message" character varying, "montant" integer NOT NULL, "code" character varying, "date_limite" TIMESTAMP NOT NULL, "restant" integer NOT NULL, "police_id" integer, "conducteur_id" integer NOT NULL, CONSTRAINT "UQ_314ac835dedef2115a73bfe3378" UNIQUE ("code"), CONSTRAINT "PK_a494b9b095f465e23f81b70094b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "constantes" ("createur_id" integer, "editeur_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" SERIAL NOT NULL, "nom" character varying NOT NULL, "valeur" character varying NOT NULL, "visibilite" character varying NOT NULL DEFAULT 'PUBLIC', "status" boolean NOT NULL DEFAULT true, "description" character varying NOT NULL, CONSTRAINT "PK_30c7f1335efeff645b9676298be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mairie_images" ("mairie_id" integer NOT NULL, "fichier_id" integer NOT NULL, CONSTRAINT "PK_0552dfb5c95fe2daa6f86d3dd28" PRIMARY KEY ("mairie_id", "fichier_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac71c8a595bcd8a8c89d3b9b77" ON "mairie_images" ("mairie_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_29b641055afe00e7053af5b6f3" ON "mairie_images" ("fichier_id") `);
        await queryRunner.query(`CREATE TABLE "users_profiles" ("user_id" integer NOT NULL, "fichier_id" integer NOT NULL, CONSTRAINT "PK_65d0e006b1d4d2d176e8a5a8785" PRIMARY KEY ("user_id", "fichier_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_181a055631e557898c3eea0f37" ON "users_profiles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7a5b3c88243b792de167a6613" ON "users_profiles" ("fichier_id") `);
        await queryRunner.query(`CREATE TABLE "vehicules_images" ("vehicule_id" integer NOT NULL, "fichier_id" integer NOT NULL, CONSTRAINT "PK_8fbceac73a92f3e9fba9b9e26b5" PRIMARY KEY ("vehicule_id", "fichier_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f1da585c718afc8b415e5ba64" ON "vehicules_images" ("vehicule_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3741916df26a83c3c9c10e2b03" ON "vehicules_images" ("fichier_id") `);
        await queryRunner.query(`CREATE TABLE "amande_types" ("amande_id" integer NOT NULL, "type_amande_id" integer NOT NULL, CONSTRAINT "PK_f6ec2be58f8a32a451552418a1e" PRIMARY KEY ("amande_id", "type_amande_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ddccb203df29a7f8dafa9694a" ON "amande_types" ("amande_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd9ddc927cf2cc5686ca60e69e" ON "amande_types" ("type_amande_id") `);
        await queryRunner.query(`CREATE TABLE "amandes_payements" ("amande_id" integer NOT NULL, "payement_id" integer NOT NULL, CONSTRAINT "PK_7753a59f0dd1e727a2645a9763b" PRIMARY KEY ("amande_id", "payement_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db10737d2118e3aa77d972b274" ON "amandes_payements" ("amande_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_214278edf9176cb8988eb38931" ON "amandes_payements" ("payement_id") `);
        await queryRunner.query(`ALTER TABLE "communes" ADD CONSTRAINT "FK_dc2adca1292f393cb5f35dd87d9" FOREIGN KEY ("departement_id") REFERENCES "departements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arrondissements" ADD CONSTRAINT "FK_654588e039586ddaea3a3e77663" FOREIGN KEY ("commune_id") REFERENCES "communes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairies" ADD CONSTRAINT "FK_564e0bf23e1e1be80b8a0489568" FOREIGN KEY ("arrondissement_id") REFERENCES "arrondissements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairies" ADD CONSTRAINT "FK_c4a3066ced3ef3846ee57d5165e" FOREIGN KEY ("localisation_id") REFERENCES "localisations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairies" ADD CONSTRAINT "FK_4ea43fd063892b8a2a21ce66cd0" FOREIGN KEY ("commune_id") REFERENCES "communes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairies" ADD CONSTRAINT "FK_8f6114a983a41e56fa95451ae63" FOREIGN KEY ("fichier_id") REFERENCES "fichiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_e12827bcc3821e08176dcaa0f9d" FOREIGN KEY ("arrondissement_id") REFERENCES "arrondissements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4db040f2277fb39a8a4864c41c2" FOREIGN KEY ("fichier_id") REFERENCES "fichiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comptes" ADD CONSTRAINT "FK_f1e9bf900b9220f91b487aeeefd" FOREIGN KEY ("id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payements" ADD CONSTRAINT "FK_ba97d5e8b21851ebc565958c9ea" FOREIGN KEY ("compte_id") REFERENCES "comptes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licences" ADD CONSTRAINT "FK_951612ce6aceb9b6fa03336d990" FOREIGN KEY ("conducteur_id") REFERENCES "conducteurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licences" ADD CONSTRAINT "FK_fbdd7a4d2586d2d94e0f911949b" FOREIGN KEY ("marie") REFERENCES "mairies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licences" ADD CONSTRAINT "FK_97df5270a0719fe1a920bc8b98a" FOREIGN KEY ("payement") REFERENCES "payements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proprietaires_vehicules" ADD CONSTRAINT "FK_deebc705df85f6bc87157678889" FOREIGN KEY ("proprietaire_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proprietaires_vehicules" ADD CONSTRAINT "FK_49d8b452db3c9390f9b33a178ed" FOREIGN KEY ("vehicule_id") REFERENCES "vehicules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conducteurs_vehicules" ADD CONSTRAINT "FK_a5f6dd6dea72b2f363cec23f45e" FOREIGN KEY ("conducteur_id") REFERENCES "conducteurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conducteurs_vehicules" ADD CONSTRAINT "FK_a01722f91e203889b59a316beab" FOREIGN KEY ("vehicule_id") REFERENCES "vehicules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licence_vehicule" ADD CONSTRAINT "FK_7c0cd751e05d28bdbca296405ab" FOREIGN KEY ("conducteur_id") REFERENCES "conducteurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licence_vehicule" ADD CONSTRAINT "FK_655063aab3b869fc767f83b7bbc" FOREIGN KEY ("vehicule_id") REFERENCES "vehicules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licence_vehicule" ADD CONSTRAINT "FK_5b73c2b7fd0da0c0d8c5e4b8be2" FOREIGN KEY ("marie") REFERENCES "mairies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicules" ADD CONSTRAINT "FK_22f6e634c68272209df52678437" FOREIGN KEY ("proprietaire_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicules" ADD CONSTRAINT "FK_49d04effd207c4c6925d19a8e82" FOREIGN KEY ("conducteur_id") REFERENCES "conducteurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicules" ADD CONSTRAINT "FK_c2ded65e232457211633065bd29" FOREIGN KEY ("licence_vehicule_id") REFERENCES "licence_vehicule"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicules" ADD CONSTRAINT "FK_682a30742b34879e5950d68bc16" FOREIGN KEY ("fichier_id") REFERENCES "fichiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appreciations" ADD CONSTRAINT "FK_e8c60bc7005159f92ec046da41a" FOREIGN KEY ("conducteur_id") REFERENCES "conducteurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appreciations" ADD CONSTRAINT "FK_2ede2bc232a8102d626b8339c23" FOREIGN KEY ("fichier_id") REFERENCES "fichiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conducteurs" ADD CONSTRAINT "FK_eab56262c5281778a6b22b2ea78" FOREIGN KEY ("conducteur_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conducteurs" ADD CONSTRAINT "FK_af0bbf1dd602dd8cf05ddd1c03b" FOREIGN KEY ("licence_id") REFERENCES "licences"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conducteurs" ADD CONSTRAINT "FK_a786ead6641eb9aae9977d670f3" FOREIGN KEY ("mairie_id") REFERENCES "mairies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conducteurs" ADD CONSTRAINT "FK_bb562b23d666b9dd4707386d208" FOREIGN KEY ("vehicule_id") REFERENCES "vehicules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "types_amandes" ADD CONSTRAINT "FK_870ff6f2c636d50ca547f0ea292" FOREIGN KEY ("fichier_id") REFERENCES "fichiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "polices" ADD CONSTRAINT "FK_c13da5ea9563bc3a99ebf321906" FOREIGN KEY ("id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amandes" ADD CONSTRAINT "FK_72f8f8455bfca28cfeec616cb9b" FOREIGN KEY ("police_id") REFERENCES "polices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amandes" ADD CONSTRAINT "FK_ef0395501d120fec128d38f7aa6" FOREIGN KEY ("conducteur_id") REFERENCES "conducteurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mairie_images" ADD CONSTRAINT "FK_ac71c8a595bcd8a8c89d3b9b779" FOREIGN KEY ("mairie_id") REFERENCES "mairies"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "mairie_images" ADD CONSTRAINT "FK_29b641055afe00e7053af5b6f32" FOREIGN KEY ("fichier_id") REFERENCES "fichiers"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_profiles" ADD CONSTRAINT "FK_181a055631e557898c3eea0f37e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_profiles" ADD CONSTRAINT "FK_a7a5b3c88243b792de167a66135" FOREIGN KEY ("fichier_id") REFERENCES "fichiers"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicules_images" ADD CONSTRAINT "FK_7f1da585c718afc8b415e5ba64d" FOREIGN KEY ("vehicule_id") REFERENCES "vehicules"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vehicules_images" ADD CONSTRAINT "FK_3741916df26a83c3c9c10e2b03e" FOREIGN KEY ("fichier_id") REFERENCES "fichiers"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "amande_types" ADD CONSTRAINT "FK_3ddccb203df29a7f8dafa9694a3" FOREIGN KEY ("amande_id") REFERENCES "amandes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "amande_types" ADD CONSTRAINT "FK_cd9ddc927cf2cc5686ca60e69ec" FOREIGN KEY ("type_amande_id") REFERENCES "types_amandes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "amandes_payements" ADD CONSTRAINT "FK_db10737d2118e3aa77d972b274e" FOREIGN KEY ("amande_id") REFERENCES "amandes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "amandes_payements" ADD CONSTRAINT "FK_214278edf9176cb8988eb38931a" FOREIGN KEY ("payement_id") REFERENCES "payements"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "amandes_payements" DROP CONSTRAINT "FK_214278edf9176cb8988eb38931a"`);
        await queryRunner.query(`ALTER TABLE "amandes_payements" DROP CONSTRAINT "FK_db10737d2118e3aa77d972b274e"`);
        await queryRunner.query(`ALTER TABLE "amande_types" DROP CONSTRAINT "FK_cd9ddc927cf2cc5686ca60e69ec"`);
        await queryRunner.query(`ALTER TABLE "amande_types" DROP CONSTRAINT "FK_3ddccb203df29a7f8dafa9694a3"`);
        await queryRunner.query(`ALTER TABLE "vehicules_images" DROP CONSTRAINT "FK_3741916df26a83c3c9c10e2b03e"`);
        await queryRunner.query(`ALTER TABLE "vehicules_images" DROP CONSTRAINT "FK_7f1da585c718afc8b415e5ba64d"`);
        await queryRunner.query(`ALTER TABLE "users_profiles" DROP CONSTRAINT "FK_a7a5b3c88243b792de167a66135"`);
        await queryRunner.query(`ALTER TABLE "users_profiles" DROP CONSTRAINT "FK_181a055631e557898c3eea0f37e"`);
        await queryRunner.query(`ALTER TABLE "mairie_images" DROP CONSTRAINT "FK_29b641055afe00e7053af5b6f32"`);
        await queryRunner.query(`ALTER TABLE "mairie_images" DROP CONSTRAINT "FK_ac71c8a595bcd8a8c89d3b9b779"`);
        await queryRunner.query(`ALTER TABLE "amandes" DROP CONSTRAINT "FK_ef0395501d120fec128d38f7aa6"`);
        await queryRunner.query(`ALTER TABLE "amandes" DROP CONSTRAINT "FK_72f8f8455bfca28cfeec616cb9b"`);
        await queryRunner.query(`ALTER TABLE "polices" DROP CONSTRAINT "FK_c13da5ea9563bc3a99ebf321906"`);
        await queryRunner.query(`ALTER TABLE "types_amandes" DROP CONSTRAINT "FK_870ff6f2c636d50ca547f0ea292"`);
        await queryRunner.query(`ALTER TABLE "conducteurs" DROP CONSTRAINT "FK_bb562b23d666b9dd4707386d208"`);
        await queryRunner.query(`ALTER TABLE "conducteurs" DROP CONSTRAINT "FK_a786ead6641eb9aae9977d670f3"`);
        await queryRunner.query(`ALTER TABLE "conducteurs" DROP CONSTRAINT "FK_af0bbf1dd602dd8cf05ddd1c03b"`);
        await queryRunner.query(`ALTER TABLE "conducteurs" DROP CONSTRAINT "FK_eab56262c5281778a6b22b2ea78"`);
        await queryRunner.query(`ALTER TABLE "appreciations" DROP CONSTRAINT "FK_2ede2bc232a8102d626b8339c23"`);
        await queryRunner.query(`ALTER TABLE "appreciations" DROP CONSTRAINT "FK_e8c60bc7005159f92ec046da41a"`);
        await queryRunner.query(`ALTER TABLE "vehicules" DROP CONSTRAINT "FK_682a30742b34879e5950d68bc16"`);
        await queryRunner.query(`ALTER TABLE "vehicules" DROP CONSTRAINT "FK_c2ded65e232457211633065bd29"`);
        await queryRunner.query(`ALTER TABLE "vehicules" DROP CONSTRAINT "FK_49d04effd207c4c6925d19a8e82"`);
        await queryRunner.query(`ALTER TABLE "vehicules" DROP CONSTRAINT "FK_22f6e634c68272209df52678437"`);
        await queryRunner.query(`ALTER TABLE "licence_vehicule" DROP CONSTRAINT "FK_5b73c2b7fd0da0c0d8c5e4b8be2"`);
        await queryRunner.query(`ALTER TABLE "licence_vehicule" DROP CONSTRAINT "FK_655063aab3b869fc767f83b7bbc"`);
        await queryRunner.query(`ALTER TABLE "licence_vehicule" DROP CONSTRAINT "FK_7c0cd751e05d28bdbca296405ab"`);
        await queryRunner.query(`ALTER TABLE "conducteurs_vehicules" DROP CONSTRAINT "FK_a01722f91e203889b59a316beab"`);
        await queryRunner.query(`ALTER TABLE "conducteurs_vehicules" DROP CONSTRAINT "FK_a5f6dd6dea72b2f363cec23f45e"`);
        await queryRunner.query(`ALTER TABLE "proprietaires_vehicules" DROP CONSTRAINT "FK_49d8b452db3c9390f9b33a178ed"`);
        await queryRunner.query(`ALTER TABLE "proprietaires_vehicules" DROP CONSTRAINT "FK_deebc705df85f6bc87157678889"`);
        await queryRunner.query(`ALTER TABLE "licences" DROP CONSTRAINT "FK_97df5270a0719fe1a920bc8b98a"`);
        await queryRunner.query(`ALTER TABLE "licences" DROP CONSTRAINT "FK_fbdd7a4d2586d2d94e0f911949b"`);
        await queryRunner.query(`ALTER TABLE "licences" DROP CONSTRAINT "FK_951612ce6aceb9b6fa03336d990"`);
        await queryRunner.query(`ALTER TABLE "payements" DROP CONSTRAINT "FK_ba97d5e8b21851ebc565958c9ea"`);
        await queryRunner.query(`ALTER TABLE "comptes" DROP CONSTRAINT "FK_f1e9bf900b9220f91b487aeeefd"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4db040f2277fb39a8a4864c41c2"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_e12827bcc3821e08176dcaa0f9d"`);
        await queryRunner.query(`ALTER TABLE "mairies" DROP CONSTRAINT "FK_8f6114a983a41e56fa95451ae63"`);
        await queryRunner.query(`ALTER TABLE "mairies" DROP CONSTRAINT "FK_4ea43fd063892b8a2a21ce66cd0"`);
        await queryRunner.query(`ALTER TABLE "mairies" DROP CONSTRAINT "FK_c4a3066ced3ef3846ee57d5165e"`);
        await queryRunner.query(`ALTER TABLE "mairies" DROP CONSTRAINT "FK_564e0bf23e1e1be80b8a0489568"`);
        await queryRunner.query(`ALTER TABLE "arrondissements" DROP CONSTRAINT "FK_654588e039586ddaea3a3e77663"`);
        await queryRunner.query(`ALTER TABLE "communes" DROP CONSTRAINT "FK_dc2adca1292f393cb5f35dd87d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_214278edf9176cb8988eb38931"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db10737d2118e3aa77d972b274"`);
        await queryRunner.query(`DROP TABLE "amandes_payements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd9ddc927cf2cc5686ca60e69e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddccb203df29a7f8dafa9694a"`);
        await queryRunner.query(`DROP TABLE "amande_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3741916df26a83c3c9c10e2b03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f1da585c718afc8b415e5ba64"`);
        await queryRunner.query(`DROP TABLE "vehicules_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7a5b3c88243b792de167a6613"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_181a055631e557898c3eea0f37"`);
        await queryRunner.query(`DROP TABLE "users_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29b641055afe00e7053af5b6f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac71c8a595bcd8a8c89d3b9b77"`);
        await queryRunner.query(`DROP TABLE "mairie_images"`);
        await queryRunner.query(`DROP TABLE "constantes"`);
        await queryRunner.query(`DROP TABLE "amandes"`);
        await queryRunner.query(`DROP TABLE "polices"`);
        await queryRunner.query(`DROP TABLE "types_amandes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3dcf8f0efa05bea701379e30ba"`);
        await queryRunner.query(`DROP TABLE "conducteurs"`);
        await queryRunner.query(`DROP TABLE "appreciations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_922bb175132122adc2c82c631b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1636cc885be3bcd2cf631f5aff"`);
        await queryRunner.query(`DROP TABLE "vehicules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa4408a1adedcf78424fab08ed"`);
        await queryRunner.query(`DROP TABLE "licence_vehicule"`);
        await queryRunner.query(`DROP TABLE "conducteurs_vehicules"`);
        await queryRunner.query(`DROP TABLE "proprietaires_vehicules"`);
        await queryRunner.query(`DROP TABLE "licences"`);
        await queryRunner.query(`DROP TABLE "payements"`);
        await queryRunner.query(`DROP TABLE "comptes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65cbf5fcb331619593ee334c7c"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "mairies"`);
        await queryRunner.query(`DROP TABLE "fichiers"`);
        await queryRunner.query(`DROP TABLE "localisations"`);
        await queryRunner.query(`DROP TABLE "arrondissements"`);
        await queryRunner.query(`DROP TABLE "communes"`);
        await queryRunner.query(`DROP TABLE "departements"`);
    }

}
